name: TexasPoker

options:
  bundleIdPrefix: smartegg
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.2"

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    DEVELOPMENT_TEAM: L7SX3PS3BS
    CODE_SIGN_STYLE: Automatic

targets:
  TexasPoker:
    type: application
    platform: iOS
    sources:
      - path: TexasPoker
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: smartegg.TexasPoker
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor

  TexasPokerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TexasPokerTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: TexasPoker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: smartegg.TexasPokerTests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TexasPoker.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/TexasPoker"
        BUNDLE_LOADER: "$(TEST_HOST)"
